### PR TITLE
Implemented ConvertColorToGrayScale filter test

### PR DESCRIPTION
**Pull request by nathanblair**
+ Added UnitTest to CMakeList file
+ Uses SetUp, RunTest, and TearDown to test filter
+ Added some empty geometries to test container array
    - Filter has no required geometries and this can be extended for
    other geometries later
+ Implemented vertex geometry data container
+ Refactored ConvertColorToGrayScale filter
    - Removed some unnecessary lines
    - Updated some ISO C++11 statements
    - Refactor algorithm choice and running
    - Fixed luminosity algorithm float to int conversion
    - Fixed lightness algorithm float to int conversion

P.S. I'm a dummy and accidentally deleted the branch so I think the last PR got deleted. Oops!

### CODE REVIEW

**Review by mmarineBlueQuartz — COMMENTED** [review]
Reiterating comments from the original pull request:
Don't forget to clang-format for quick formatting.  Curly brackets go on their own line for `if else for while`.  Change the structs at the top of ConvertColorToGrayScale.cpp to classes and put them in their own namespace, even if it doesn't get a name, to prevent generic names like Functor from clashing with anything else.  Use `=` for initialization instead of `{0}`.  Use switch statements for enums instead of chaining `else if`.

See [original](https://github.com/BlueQuartzSoftware/DREAM3D/pull/866) for more details.

**Comment by imikejackson** [comment]
Well, I happen to have that branch on my working copy.

**Review by nathanblair — COMMENTED** [review]
This integrates changes from the main develop branch

**Comment by imikejackson** [comment]
Go back to the other PR and pull from @imikejackson fork of this branch. The unit tests are failing and need to be checked and fixed.

**Pull request closed without merging**
