### PR TITLE
Changes to insert atom feature

### PR DESCRIPTION
**Pull request by MicroClue**
There was a typo that caused a crash when there are a high number (>200) of features in the system. Also, I added the ability to set the basis to cubic crystal.

Details described here: https://groups.google.com/forum/#!topic/dream3d-users/Z2YbAaQHMUQ

### CODE REVIEW

**Review by imikejackson — COMMENTED** [review]
On the whole looks good. There are a few items that need to be fixed:
coords[] is a float which means there will be compiler warnings when the 0.5 is used. Can you use 0.5f  or 0.25f instead which tells the compiler those are floating point values instead of doubles.

Somewhere in the data check there really should be a sanity check on the value for the "Basis" to make sure that it falls between 0 and 3.

**Comment by imikejackson** [comment]
Also when you commit the code please use the "-s" flag so that a "signed off by" is added to the commit comment. We need this to allows to eventually merge the codes into the main line branch.

**Comment by MicroClue** [comment]
Yeah, agreed on the double->float change. 

For the value of "basis", the dream3d ui has the user choose between "Simple Cubic"..."Cubic Diamond" rather then choose the basis value directly. So i don't think that it will ever not fall between 0-3.

I added the "-s" flag to my last commit but unsure how to do it to the commits i made before that.

Finally, as we discussed in the google group post, there needs to be some better understanding on what value should be used for the lattice constant values. But I'm too unfamiliar with the code to make any substantial code changes on that front...that being said, removing "(Angstroms)" (line 307) would force the user to figure out what units to use rather than assume incorrectly that the units should be angstrom.

**Comment by imikejackson** [comment]
The issue is that DREAM.3D could be reading a pipeline file that has been adjusted outside of DREAM.3D or a user is creating a pipeline file and using PipelineRunner to just run the pipeline. In that case there is no UI to help the user select the proper values which is why we have the sanity check in the dataCheck() method. It should have been there from the start of the filter but got left out when the origin filter was written.

We have been adding some more information to the Synthetic Initialization filter to allow the user to set the length units that are being used. Note that this is just for descriptive purposes at this point. To add to that we also now calculate the volume of the ImageGeom and display that when you hover over the Data Structure widget on top of the Data Container. These are small but can help the user better determine how much space they are trying to fill. @mgroeber and I also discussed adding some filter parameters that just let the user know how many atoms they are going to create. There is a PreflightUpdatedValueFilterParameter that one can put into the filter that will display a string in the user interface. Take a look at the "InitializeSyntheticVolume" filter. If you check the box to "Estimate Number of Feature" this is that filter parameter in action. We were thinking that we could at least display a "worst case" scenario for the number of atoms that would be created if the feature were aligned properly and there was only a single feature in the volume.

Thoughts?

**Comment by MicroClue** [comment]
I'm never against a feature that could be potentially useful, estimating number of atoms would be useful where there are computational concerns (eg running it with DFT or MD). From a design standpoint, I would prefer it be a button to calculate (like "create data" in statsgenerator) rather than a checkbox, since the dynamic calculation might lag behind the parameters being changed. I've personally experienced my screen freezing when I try to change the volume (and the volume size is already large) while leaving the checkbox on.

**Comment by imikejackson** [comment]
@MicroClue Could you expand more a bit on the scree freezing issue? We are striving to make DREAM.3D as fast as we can. What is your OS, Hardware specs, and anything else that you think we might need to diagnose the issue? How large was the pipeline (number of filters and number of data containers) when the freezing occurred?

**Comment by MicroClue** [comment]
Regarding the screen freezing issue, it happens when the total feature numbers are high, like >10000. It only freezes during the dynamic calculation of the number of features when I edit the volume size. I think my system is modern, but I am using x11 forwarding or xpra over bare metal.

**Pull request merged**
